name: tempo
description: "Tempo: Una herramienta de bienestar digital enfocada en la gestión
  de la intención y reducción de la distracción en Android."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^17.3.0
  usage_stats: ^1.3.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
