class QuotesConstants {
  static const List<String> wellnessQuotes = [
    "«¿Ese celular te está haciendo compañía o te está quitando la vida? ¡Quédate con lo segundo!»",
    "«¡Quieto ahí! ¿Esto es importante o es que te gusta gastar los minutos a lo loco?»",
    "«El tiempo no se recupera ni con recargas. ¡Disfruta lo que tienes frente a tus ojos!»",
    "«Qué belleza es la vida real. Deja el aparato un ratico y sal a ver el sol.»",
    "«¿Estás aquí buscando algo o solo tratando de que el tiempo pase más rápido?»",
    "«La vida es un ratico, y te la estás pasando viendo la pantalla. ¡Despierta, que el mundo es hermoso!»",
    "«¿Qué tal si dejas el celular y te tomas un tintico con calma? Eso sí es vida.»",
    "«No dejes que una notificación te quite la paz que tanto te ha costado conseguir.»",
    "«¡Qué vaina tan buena es estar presente! Aprovecha este momento que es solo tuyo.»",
    "«¿Ya diste gracias por el día de hoy? ¡Deja el celu y mira a tu alrededor!»",
    "«El scroll infinito es como comer sin hambre. ¡Aprende a decir basta!»",
    "«La felicidad no se encuentra en las aplicaciones, se encuentra en los momentos simples.»",
    "«¡Pégate una estiradita! El cuerpo también pide que lo cuides un poquito.»",
    "«No confundas estar conectado con el mundo, con estar conectado contigo mismo.»",
    "«Esa pantalla no te va a devolver las horas que estás dejando pasar. ¡Cierra y vive!»",
    "«¿Qué estás postergando por estar aquí? ¡Anímate, que tú puedes con eso!»",
    "«A veces, lo más sabio es simplemente soltar, respirar y volver a empezar.»",
    "«El mundo sigue dando vueltas afuera. ¡Sal a ver qué tal está la brisa!»",
    "«No te vuelvas esclavo de lo que sale en la pantalla, tú naciste para ser libre.»",
    "«¿Y si en vez de scrollear, planeas algo que te haga sonreír hoy?»",
    "«El tiempo vuela, pero tú eres el piloto. ¡Toma el control de tu nave!»",
    "«¿De verdad esto es lo que quieres hacer ahora o es solo por costumbre?»",
    "«Un respiro profundo hace más por ti que mil notificaciones juntas.»",
    "«Disfruta de la calma, que el ruido de las redes siempre estará ahí esperando.»",
    "«No dejes para mañana la vida que puedes disfrutar hoy mismo.»",
    "«Tú vales mucho más que los 'likes' que recibas en una aplicación.»",
    "«¡Qué nota es estar presente! Date ese regalo, te lo mereces.»",
    "«Deja el celular a un lado y escucha el silencio, ahí es donde están las mejores respuestas.»",
    "«Si la app te está quitando la alegría, es hora de cerrar y buscar cosas mejores.»",
    "«Vive tu vida a tu ritmo, sin presiones. ¡Eres una bendición!»"
  ];
}